### ISSUE TITLE
Gränssnitt

### ISSUE THREAD

**Issue by ib222dp** [Grenmyr/1DV450Angular#4]
Gränssnittet ger ett proffsigt intryck, och det är responsivt. Bra rätt-och felmeddelanden ges och kartan uppdateras när en resurs ändras. Det är lätt att som användare förstå hur applikationen ska användas, men det skulle vara bra med en rubrik så att man vet direkt vad det handlar om. När man kommer till startsidan står det "find by categories" och "search by plant species", men inte vad det är man kan hitta/söka efter:) Så en rubrik typ "Mushroom/berry places" skulle vara bra.
Man skulle även i den röda markern i kartan kunna ha en beskrivning av eller ett namn på stället, förutom "richness" och "added by".

**Comment by Grenmyr** [comment]
Tar tacksamt emot dina iddeer. Tycker det du säger om min sök och find skulle kunna döpas om för tydlighet är helt rätt. Beskrivning av art tycker jag att jag skriver ut eftersom det står kantarell, rönnbär eller whatever på headern av varje vy av kartan. Men kanske skulle man lägga in artnamn i marker också. Det är alltid bra att vara tydlig. Det är alltid svårt med användarvänlighet.

**Comment by ib222dp** [comment]
Jag tänkte mer att man skulle kunna ha en beskrivning av själva svamp/bärstället, typ "i skogsdungen mittemot det stora gula huset" eller något sånt.

**Comment by Grenmyr** [comment]
Ahaaaa, jaaaa vilken bra ide, en lite infowindow typ. Får se om jag orkar, men bra ide!
