### ISSUE TITLE
Övrigt

### ISSUE THREAD

**Issue by ib222dp** [Grenmyr/1DV450Angular#5]
1. Inloggnings- och registreringsfönstret stängs inte när man klickar på krysset i högra hörnet.
2. I koden så klagar Nitrous på att "angular", "console", och "sessionStorage" är "not defined", vilket verkar bero på "use strict", eftersom Nitrous slutar klaga om man tar bort "use strict". Jag föreslår inte att du ska ta bort use strict, men det kanske finns något sätt att fortsätta använda use strict och ändå inte få de där varningarna? Jag hittade det här när jag googlade lite, du kanske redan har hittat det själv: http://stackoverflow.com/questions/12957625/angularjs-controllers-and-use-strict 
3. Det hade varit bra med lite fler kommentarer i koden, och det finns några tomma filer som kan tas bort. Stressigt på slutet kanske?:)

**Comment by Grenmyr** [comment]
1. Skit också, Råkade städa för mycket kod, trodde inte den användaes. Nu funkar det igen, tack.
2. Jag hade missat ta bort 3 st console log, tack!, jag hittar inte den sista undefined sessionStorage. När kom det, vet du i vilken fil den var?
3. Ja, alltså förlåt, det var jättestressigt, jag satt till 23:30, jag ville verkligen publisera apiet och det strulade massa. Tog tid, kul att apiet funkade för dig iaf, när John skulle testa hade servern krashat :-) Jag hade behövt några dagar till för leverera som jag velat, hade jag haft tid hade jag velat skapacrud på arter också, samt fixa ett rankingsystem där användare rnakas efter hur många findings de rapporterat, typ ett tävligs/ranking för pusha att fler delar., du har helt rätt annars, jag var stressad.

**Comment by Grenmyr** [comment]
Jag har åtgärdat dina buggar du hittade, tack, jag stänger issuen.
