### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ib222dp** [Grenmyr/1DV450Angular#6]
På det stora hela tycker jag att applikationen fungerar bra och att koden är bra skriven och bra strukturerad. Inloggning, registrering och sökfunktion fungerar bra, och man kan klicka sig framåt och bakåt i applikationen och även uppdatera sidan utan problem. Det var också lätt att få igång applikationen genom att följa installationsanvisningarna steg för steg.

**Comment by Grenmyr** [comment]
Kul att höra, ja vi får se, jag har inte uppfyllt alla krav som john ville ha dom. Men jag har gjort lite extra, som registrering samt fickat stöd för bookmarks och historik. Vill tacka för en bra peer review av dig, den var saklig och tydlig. Lycka till framöver.

Stänger denna issue.
